language: perl
perl:
  - "5.18"
  - "5.14"

install:
    - "cpanm -v --installdeps --notest ./" 

before_install:
    - "sudo apt-get install -qq node"
    - "sudo $(which npm) install -g less"

script: "perl Makefile.PL && make test"
